<a href="https://colab.research.google.com/github/aaaraafaat/ML--Learning_Base/blob/main/GenAI_for_DS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Practice GenAI for DS from IBM DS Course

In [ ]:
source="https://raw.githubusercontent.com/aaaraafaat/Data-Science/refs/heads/main/used_car_price_analysis.csv"

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv(source)
df.head(5)

,model,year,transmission,mileage,fuelType,tax,mpg,engineSize,price
0,Fiesta,2017,Automatic,15944,Petrol,150.0,57.7,1.0,12000
1,Focus,2018,Manual,9083,Petrol,150.0,57.7,1.0,14000
2,Focus,2017,Manual,12456,Petrol,150.0,57.7,1.0,13000
3,Fiesta,2019,Manual,10460,Petrol,145.0,40.3,1.5,17500
4,Fiesta,2019,Automatic,1482,Petrol,145.0,48.7,1.0,16500

In [ ]:
def preprocess_df(df: pd.DataFrame) -> pd.DataFrame:
  # 1. Identify columns with missing values
  cols_with_missing = df.columns[df.isnull().any()].tolist()
  print("Columns with missing values:", cols_with_missing)

  # 2. Replace missing values with the column mean (only for numeric columns)
  df = df.copy()
  numeric_cols = df.select_dtypes(include=[np.number]).columns
  df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].mean())

  # 3. Delete duplicate entries
  df = df.drop_duplicates()

  return df

In [ ]:
preprocess_df(df)

Columns with missing values: ['tax']

,model,year,transmission,mileage,fuelType,tax,mpg,engineSize,price
0,Fiesta,2017,Automatic,15944,Petrol,150.0,57.7,1.0,12000
1,Focus,2018,Manual,9083,Petrol,150.0,57.7,1.0,14000
2,Focus,2017,Manual,12456,Petrol,150.0,57.7,1.0,13000
3,Fiesta,2019,Manual,10460,Petrol,145.0,40.3,1.5,17500
4,Fiesta,2019,Automatic,1482,Petrol,145.0,48.7,1.0,16500
...,...,...,...,...,...,...,...,...,...
17961,B-MAX,2017,Manual,16700,Petrol,150.0,47.1,1.4,8999
17962,B-MAX,2014,Manual,40700,Petrol,30.0,57.7,1.0,7499
17963,Focus,2015,Manual,7010,Diesel,20.0,67.3,1.6,9999
17964,KA,2018,Manual,5007,Petrol,145.0,57.7,1.2,8299
17965,Focus,2015,Manual,5007,Petrol,22.0,57.7,1.0,8299

Fit a linear regression model to predict the price using the feature mpg. Then calculate the R^2 and MSE values for the model.

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error

In [ ]:
# Drop rows with missing values in these columns
df_clean = df[['price', 'mpg']].dropna()

X = df_clean[['mpg']].values  # feature(s)
y = df_clean['price'].values  # target

# Split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Fit the linear regression model
model = LinearRegression()
model.fit(X_train, y_train)

# Predict on the test set
y_pred = model.predict(X_test)

# Calculate R^2 and MSE
r2 = r2_score(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)

print("R^2 on test set:", r2)
print("MSE on test set:", mse)

# Optional: model coefficients
print("Slope (coefficient for mpg):", model.coef_[0])
print("Intercept:", model.intercept_)

R^2 on test set: 0.13252097840163624
MSE on test set: 19441984.663323063
Slope (coefficient for mpg): -159.31159719312535
Intercept: 21528.690014033098

Fit a linear regression model to predict the price using the following set of features.
year, mileage, tax, mpg and engineSize.
Calculate the R^2 and MSE values for this model.

In [ ]:
features = ['year', 'mileage', 'tax', 'mpg', 'engineSize']
target = 'price'

# Create a copy and drop rows with any missing values in the selected columns
df_model = df[features + [target]].dropna()

X_multi = df_model[features].values
y_multi = df_model[target].values

# Split the data into train and test sets
X_train_multi, X_test_multi, y_train_multi, y_test_multi = train_test_split(X_multi, y_multi, test_size=0.2, random_state=42)

# Fit the linear regression model
model_multi = LinearRegression()
model_multi.fit(X_train_multi, y_train_multi)

# Predict on the test set
y_pred_multi = model_multi.predict(X_test_multi)

# Calculate R^2 and MSE
r2_multi = r2_score(y_test_multi, y_pred_multi)
mse_multi = mean_squared_error(y_test_multi, y_pred_multi)

print("R^2 on test set (multi-feature model):", r2_multi)
print("MSE on test set (multi-feature model):", mse_multi)

# Optional: model coefficients
print("Coefficients:", model_multi.coef_)
print("Intercept:", model_multi.intercept_)

R^2 on test set (multi-feature model): 0.7297707848827808
MSE on test set (multi-feature model): 6125901.226911344
Coefficients: [ 1.22120095e+03 -5.80860689e-02  5.78370881e-01 -8.08439457e+01
  5.33276096e+03]
Intercept: -2451960.3242574767

Alternate Code output from ChatGPT

In [ ]:
# 1. Prepare data: select features and target, drop rows with missing values
cols = ['price', 'year', 'mileage', 'tax', 'mpg', 'engineSize']
df_clean = df[cols].dropna()

X = df_clean[['year', 'mileage', 'tax', 'mpg', 'engineSize']]
y = df_clean['price']

# 2. Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 3. Fit linear regression model
model = LinearRegression()
model.fit(X_train, y_train)

# 4. Predict on test set
y_pred = model.predict(X_test)

# 5. Calculate R^2 and MSE
r2 = r2_score(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)

print("R^2 on test set:", r2)
print("MSE on test set:", mse)
print("Coefficients:", model.coef_)
print("Intercept:", model.intercept_)

R^2 on test set: 0.7297707848827826
MSE on test set: 6125901.226911305
Coefficients: [ 1.22120095e+03 -5.80860689e-02  5.78370881e-01 -8.08439457e+01
  5.33276096e+03]
Intercept: -2451960.3242574753

For the same set of features as in the question above, create a pipeline model object that uses standard scalar, second degree polynomial features and a linear regression model. Calculate the R^2 value and the MSE value for this model. Collab AI

In [ ]:
from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn.pipeline import Pipeline

features = ['year', 'mileage', 'tax', 'mpg', 'engineSize']
target = 'price'

# Prepare data: select features and target, drop rows with missing values
df_model_pipeline = df[features + [target]].dropna()

X_pipeline = df_model_pipeline[features]
y_pipeline = df_model_pipeline[target]

# Split the data into train and test sets
X_train_pipeline, X_test_pipeline, y_train_pipeline, y_test_pipeline = train_test_split(X_pipeline, y_pipeline, test_size=0.2, random_state=42)

# Create the pipeline
pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('poly', PolynomialFeatures(degree=2)),
    ('linear_regression', LinearRegression())
])

# Fit the pipeline model
pipeline.fit(X_train_pipeline, y_train_pipeline)

# Predict on the test set
y_pred_pipeline = pipeline.predict(X_test_pipeline)

# Calculate R^2 and MSE
r2_pipeline = r2_score(y_test_pipeline, y_pred_pipeline)
mse_pipeline = mean_squared_error(y_test_pipeline, y_pred_pipeline)

print("R^2 on test set (pipeline model):", r2_pipeline)
print("MSE on test set (pipeline model):", mse_pipeline)

R^2 on test set (pipeline model): 0.7556515409912363
MSE on test set (pipeline model): 5539203.169377451

For the same set of features, split the data into training and testing data parts. Assume testing part to be 20%. Create and fit a Ridge regression object using the training data, set the regularization parameter to 0.1, and calculate the R^2 using the test data.

In [ ]:
from sklearn.linear_model import Ridge

features = ['year', 'mileage', 'tax', 'mpg', 'engineSize']
target = 'price'

# Prepare data: select features and target, drop rows with missing values
df_ridge = df[features + [target]].dropna()

X_ridge = df_ridge[features]
y_ridge = df_ridge[target]

# Split the data into train and test sets
X_train_ridge, X_test_ridge, y_train_ridge, y_test_ridge = train_test_split(X_ridge, y_ridge, test_size=0.2, random_state=42)

# Create and fit a Ridge regression object
# Set the regularization parameter (alpha) to 0.1
ridge_model = Ridge(alpha=0.1)
ridge_model.fit(X_train_ridge, y_train_ridge)

# Predict on the test set
y_pred_ridge = ridge_model.predict(X_test_ridge)

# Calculate R^2 using the test data
r2_ridge = r2_score(y_test_ridge, y_pred_ridge)

print("R^2 on test set (Ridge regression):", r2_ridge)

R^2 on test set (Ridge regression): 0.7297705041777673

Write a Python code that can perform the following tasks.

1. Assuming that a subset of the attributes of a data frame are source attributes and one of the attributes is a target attribute, split the data into training and testing data assuming the testing data to be 20%.
2. Create and fit a Ridge regression model using the training data, setting the regularization parameter to 0.1.
3. Calculate the MSE and R^2 values for the Ridge Regression model using the testing data.

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Ridge
from sklearn.metrics import r2_score, mean_squared_error
import pandas as pd

# Assuming 'df' is your DataFrame, loaded and preprocessed as in previous steps.
# Define source attributes (features) and target attribute
features = ['year', 'mileage', 'tax', 'mpg', 'engineSize']
target = 'price'

# Prepare data: select features and target, drop rows with missing values
# This ensures consistency and handles potential NaNs before splitting
df_model = df[features + [target]].dropna()

X = df_model[features]
y = df_model[target]

# 1. Split the data into training and testing data (20% for testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 2. Create and fit a Ridge regression model using the training data
# Set the regularization parameter (alpha) to 0.1
ridge_model = Ridge(alpha=0.1)
ridge_model.fit(X_train, y_train)

# Predict on the test set
y_pred = ridge_model.predict(X_test)

# 3. Calculate the MSE and R^2 values for the Ridge Regression model using the testing data
r2 = r2_score(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)

print("Ridge Regression Model Performance:")
print(f"  R^2 on test set: {r2:.4f}")
print(f"  MSE on test set: {mse:.2f}")
print("  Coefficients:", ridge_model.coef_)
print("  Intercept:", ridge_model.intercept_)

Ridge Regression Model Performance:
  R^2 on test set: 0.7298
  MSE on test set: 6125907.59
  Coefficients: [ 1.22119754e+03 -5.80848914e-02  5.78628641e-01 -8.08460295e+01
  5.33253134e+03]
  Intercept: -2451953.089033512

Write a Python code that can perform the following tasks.

1. Assuming that a subset of the attributes of a data frame are source attributes and one of the attributes is a target attribute, split the data into training and testing data assuming the testing data to be 20%.
2. Apply second degree polynomial scaling to the training and testing data.
3. Create and fit a Ridge regression model using the training data, setting the regularization parameter to 0.1.
4. Calculate the MSE and R^2 values for the Ridge Regression model using the testing data.

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Ridge
from sklearn.metrics import r2_score, mean_squared_error
from sklearn.preprocessing import PolynomialFeatures, StandardScaler
from sklearn.pipeline import Pipeline
import pandas as pd

# Assuming 'df' is your DataFrame, loaded and preprocessed as in previous steps.
# Define source attributes (features) and target attribute
features = ['year', 'mileage', 'tax', 'mpg', 'engineSize']
target = 'price'

# Prepare data: select features and target, drop rows with missing values
df_model = df[features + [target]].dropna()

X = df_model[features]
y = df_model[target]

# 1. Split the data into training and testing data (20% for testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a pipeline with PolynomialFeatures, StandardScaler, and Ridge Regression
pipeline_poly_ridge = Pipeline([
    ('poly_features', PolynomialFeatures(degree=2)),
    ('scaler', StandardScaler()),
    ('ridge', Ridge(alpha=0.1))
])

# 3. Create and fit a Ridge regression model using the training data
#    The pipeline handles the polynomial transformation and scaling automatically
pipeline_poly_ridge.fit(X_train, y_train)

# Predict on the test set
y_pred = pipeline_poly_ridge.predict(X_test)

# 4. Calculate the MSE and R^2 values for the Ridge Regression model using the testing data
r2 = r2_score(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)

print("Ridge Regression Model with Polynomial Features Performance:")
print(f"  R^2 on test set: {r2:.4f}")
print(f"  MSE on test set: {mse:.2f}")

Ridge Regression Model with Polynomial Features Performance:
  R^2 on test set: 0.7471
  MSE on test set: 5732844.35